//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiaAttendanceSchedule.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Setting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Setting() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiaAttendanceSchedule.Resources.Setting", typeof(Setting).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7c7b9486-0cc7-44e0-950e-4a4f6435ea89.
        /// </summary>
        internal static string AuthKey {
            get {
                return ResourceManager.GetString("AuthKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://lia-hr-prs.azurewebsites.net/api/employee?mode=create-attendance-from-machine.
        /// </summary>
        internal static string HostAttendance {
            get {
                return ResourceManager.GetString("HostAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://lia-general-data.azurewebsites.net/api/branch.
        /// </summary>
        internal static string HostBranch {
            get {
                return ResourceManager.GetString("HostBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://lia-hr-prs.azurewebsites.net/api/employee?usingorincriteria=true&amp;.
        /// </summary>
        internal static string HostEmployee {
            get {
                return ResourceManager.GetString("HostEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://lia-general-data.azurewebsites.net/api//Enumeration?Criteria=EnumerationGroup:MailConfiguration.
        /// </summary>
        internal static string HostMail {
            get {
                return ResourceManager.GetString("HostMail", resourceCulture);
            }
        }
    }
}
